### ISSUE TITLE
Problems with pgltools merge

### ISSUE THREAD

**Issue by leomorelli** [billgreenwald/pgltools#11]
Hi, I'm new in the field, so sorry if I am missing something. I have some problems with pgltools merge. In particular, with pgltools intersect1D, I have obtained the following file:
`cat file.bed | head -10`

> chr1    950000  975000  chr1    1200000 1225000 A
chr1    950000  975000  chr1    1200000 1225000 B
chr1    950000  975000  chr1    1200000 1225000 B
chr1    950000  975000  chr1    1200000 1225000 B
chr1    1050000 1075000 chr1    1150000 1175000 A
chr1    1050000 1075000 chr1    1150000 1175000 A
chr1    1050000 1075000 chr1    1150000 1175000 B
chr1    1050000 1075000 chr1    1150000 1175000 B
chr1    1050000 1075000 chr1    1150000 1175000 B
chr1    1075000 1100000 chr1    1150000 1175000 B

However, once I use pgltools merge I obtain the following error:
`programs/pgltools/sh/pgltools merge -a file.bed -o collapse -c 7 -noH > new_file.bed`

> Traceback (most recent call last):
  File "programs/pgltools/sh/../Python/merge.py", line 355, in <module>
    merge(A,args,header)
  File "programs/pgltools/sh/../Python/merge.py", line 270, in merge
    reMerge=_merge(sorted(res),[x-1 for x in cols],commands,args['d'])
TypeError: '<' not supported between instances of 'list' and 'str'

**Comment by leomorelli** [comment]
My fault. I was working in a conda environment, which uses python3.

**Comment by billgreenwald** [comment]
No worries, glad you figured it out quickly.  

As a side note, the project probably needs an update to Python 3, along with some regression testing framework, if anyone ever stumbles upon this issue and wants to write a PR.
