### ISSUE TITLE
intersect1D "UnboundLocalError: local variable 'Aannots' referenced before assignment" error triggered by Inter-chromosomal interactions

### ISSUE THREAD

**Issue by SplitInf** [billgreenwald/pgltools#12]
Hi,

Thanks for making the tool available to the community. I noticed a bug when running intersect1D when the -b file contains a target that intersects with a inter-chrom interaction event. A workaround I noticed was if you add a dummy intra-chrom interaction into -a and -b file this error wouldn't be triggered. [pgltools 2.2.0]

- intra-chrom interactions only bedpe
```
cat toy1.bedpe 
chr1	710000	715000	chr1	935000	940000	
chr1	825000	830000	chr1	935000	940000
```

- intra and inter chrom interactions bedpe
```
cat toy2.bedpe 
chr1	710000	715000	chr1	935000	940000	
chr1	825000	830000	chr1	935000	940000
chr1	920000	925000	chr2	935000  940000
```

- bed region corresponds to intra-chrom region
```
cat targ1.bed 
chr1    935000  940000
chr2    935000  940000
```

- bed region corresponds to inter-chrom region
```
cat targ2.bed 
chr2    935000  940000
```

- intersect intra-chrom with intra-chrom only file -> works
```
pgltools intersect1D -a toy1.bedpe -b targ1.bed -wa
chr1	710000	715000	chr1	935000	940000	B	
chr1	825000	830000	chr1	935000	940000	B	
```

- intersect intra-chrom target with intra and inter chrom file -> works
```
pgltools intersect1D -a toy2.bedpe -b targ1.bed -wa
chr1	710000	715000	chr1	935000	940000	B	
chr1	825000	830000	chr1	935000	940000	B	
chr1	920000	925000	chr2	935000	940000	B	
```

- intersect inter-chrom target with intra and inter chrom file -> error
```
pgltools intersect1D -a toy2.bedpe -b targ2.bed -wa
Traceback (most recent call last):
  File "intersect1D.py", line 403, in <module>
    intersect1D(A,B,args,header,headerB)
  File "intersect1D.py", line 272, in intersect1D
    res=_overlap1D(A,B,args['bA'],args['allA'],args['wa'],args['d'],args['v'],args['wb'],args['u'])
  File "intersect1D.py", line 258, in _overlap1D
    newPeaks.append([[chr1,start1,end1,chr2,start2,end2,"B"],Aannots])
UnboundLocalError: local variable 'Aannots' referenced before assignment
```

**Comment by SplitInf** [comment]
i̶s̶s̶u̶e̶s̶ ̶r̶e̶s̶o̶l̶v̶e̶d̶ ̶w̶i̶t̶h̶ ̶f̶o̶r̶m̶a̶t̶b̶e̶d̶p̶e̶

**Comment by SplitInf** [comment]
Nope, problem persisted. It's not because of sorting.

**Comment by billgreenwald** [comment]
Hey I am getting around to responding to some of these, apologies for it being so long.  Still having an issue/using the tool?

**Comment by auberginekenobi** [comment]
Hi Bill, 
Yep, just encountered the same problem with the same use case.

**Comment by SplitInf** [comment]
Hi Bill, yes this is still a problem. Sorry for the poorly worded description, but the examples should help.

**Comment by SplitInf** [comment]
erkk, sorry closed ticket by mistake.

**Comment by billgreenwald** [comment]
Should be fixed in 5662fa4e0c85702e6a1247a662cfaedb473f9965, try pulling and running

**Comment by billgreenwald** [comment]
This is also added as an explicit test case in the above push, and is pulled in to the 3.0.0 update, so this shouldnt be a problem.  If any other behaviors come up let me know since its now easy to just add more tests.

If one of the original commenters can confirm it now works for them, please close when you comment back :)

**Comment by SplitInf** [comment]
seems to work now! thank you
