### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'.

### ISSUE THREAD

**Issue by DittmanC** [billgreenwald/pgltools#13]
File "/software/pgltools/sh/../Python/intersect.py", line 265
    print "stdin can only be used for either a or b"
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("stdin can only be used for either a or b")?

I wonder is it because I cannot successfully install the package?

**Comment by billgreenwald** [comment]
I would guess you are on python3 and I wrote pgltools in python 2.7. Python 3 requires parentheses around print statements. Try a python 2.7 kernel and see if it works

**Comment by billgreenwald** [comment]
The new updated to 3.0.0 should also fix you by just using Python3.  I updated it this weekend.  I am closing but let me know if you have other problems
