### ISSUE TITLE
TypeError: formatbedpe() missing 1 required positional argument: 'header'

### ISSUE THREAD

**Issue by WangxiaowuLab** [billgreenwald/pgltools#19]
Hello!
I meet a problem when convert the bedpe format to pgl format using pgltools formatbedpe. Can you help me ?
The error is as followed:
(base) [zhanglp@bogon test_pgl]$ pgltools formatbedpe test.bedpe 
Traceback (most recent call last):
  File "/43t/zhanglp/biosoft/pgltools/pgltools-3.0.1/sh/../Module/PyGLtools/column_flip.py", line 130, in <module>
    formatbedpe(A)
TypeError: formatbedpe() missing 1 required positional argument: 'header'

And the test.bepe is the same as  your Proper Formatting.

**Comment by billgreenwald** [comment]
Hey there, sorry about that.  Seems I created a syntax error when I upgraded to version 3.0.0.  This has been fixed in 3.0.1 and tests are added to hopefully capture in the future.  Let me know if something else doesn't work and I will try to fix it ASAP as well.

Fixed in:
https://github.com/billgreenwald/pgltools/pull/20

**Comment by WangxiaowuLab** [comment]
Thank you very much!
The problem have been fixed in 3.0.1 that you recently published




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "billgreenwald/pgltools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月23日(星期三) 晚上11:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [billgreenwald/pgltools] TypeError: formatbedpe() missing 1 required positional argument: 'header' (Issue #19)





 
Hey there, sorry about that.  Seems I created a syntax error when I upgraded to version 3.0.0.  This has been fixed in 3.0.1 and tests are added to hopefully capture in the future.  Let me know if something else doesn't work and I will try to fix it ASAP as well.
 
Fixed in:
 #20
