### ISSUE TITLE
Sorting command is not available

### ISSUE THREAD

**Issue by sb5169** [billgreenwald/pgltools#2]
Hi I am trying to use
PyGLtools/intersect.py

but I keep getting the follow error:
File A is not sorted.  Please use pgltools sort [FILE]

the top of file A is shown below.

and I cannot find the sort or fomartbedpe command:
__init__.py		closest.pyc		condense.py		coverage.pyc		formatTripSparse.py	intersect1D.pyc		pgltools_library.py	subtract.pyc
__init__.pyc		closest1D.py		condense.pyc		expand.py		formatTripSparse.pyc	juicebox.py		pgltools_library.pyc	subtract1D.py
browser.py		closest1D.pyc		conveRt.py		expand.pyc		intersect.py		juicebox.pyc		samTopgl.py		subtract1D.pyc
browser.pyc		column_flip.py		conveRt.pyc		findLoops.py		intersect.pyc		merge.py		samTopgl.pyc		window.py
closest.py		column_flip.pyc		coverage.py		findLoops.pyc		intersect1D.py		merge.pyc		subtract.py		window.pyc

#chrA	startA	stopA	chrB	startB	stopB	AnnotationA	AnnotationB
chr1	6405000	6420000	chr1	6430000	6445000	chr1:6405000:6420000	chr1:6430000:6445000
chr1	6340000	6355000	chr1	6470000	6485000	chr1:6340000:6355000	chr1:6470000:6485000
chr1	6470000	6485000	chr1	6485000	6500000	chr1:6470000:6485000	chr1:6485000:6500000
chr1	6485000	6500000	chr1	6545000	6560000	chr1:6485000:6500000	chr1:6545000:6560000
chr1	6630000	6645000	chr1	6695000	6710000	chr1:6630000:6645000	chr1:6695000:6710000
chr1	6720000	6735000	chr1	6735000	6750000	chr1:6720000:6735000	chr1:6735000:6750000
chr1	6720000	6735000	chr1	7740000	7755000	chr1:6720000:6735000	chr1:7740000:7755000
chr1	9575000	9590000	chr1	9860000	9875000	chr1:9575000:9590000	chr1:9860000:9875000
chr1	10205000	10220000	chr1	10295000	10310000	chr1:10205000:10220000	chr1:10295000:10310000

**Comment by sb5169** [comment]
just sorted manually:
 sort -k1,1 -k2,2n -k3,3n -k4,4 -k5,5n -k6,6n

**Comment by billgreenwald** [comment]
Hey there,

glad you got the issue taken care of through manually sorting, but I wanted to check in to fix any outstanding issues.

Above you typed "fomartbedpe" rather than "formatbedpe".  Was that a typo in your posting here?

Alternatively, the tool is set up to be run from the /sh folder, rather than running the python directly.  The sort commands are written in bash rather than python.

If you go into pgltools/sh/ and run
```
pgltools formatbedpe [FILE]
```

does this work?

Thanks!

**Comment by sb5169** [comment]
Hey,


Yes that was a typo. Good to know I'll try that next time.


Thanks!



Sana B. Badri
Skok & Bonneau Lab
New york University Langone medical center / NYU School of Medicine
550 First Avenue, Smilow research building, room 307
New York, NY 10016
mobile. 551-221-5882
E-mail: sana.badri@nyumc.org

________________________________
