### ISSUE TITLE
subtract "-A" option

### ISSUE THREAD

**Issue by nariai** [billgreenwald/pgltools#7]
Hi @billgreenwald , I found the pgltools extremely useful for comparing inter-chromosomal translocations that are predicted with two different methods.

Now, I want to only extract entries in file A, that do not overlap at all with any entry in file B.
Could you add "-A" option in the subtract operation, as in bedtools??
https://bedtools.readthedocs.io/en/latest/content/tools/subtract.html

Thanks.

**Comment by billgreenwald** [comment]
Hey naoki,

Use pgltools intersect -v to get this interaction.  it will report all entries in A that do not overlap entries in B.  This is similar to the bedtools intersect -v option, and since it is the same as the bedtools subtract -A option, I only put it in one place.

Bill

**Comment by nariai** [comment]
Got it, thanks!
I somehow didn't notice "-v" option.
