### ISSUE TITLE
formatbedpe error

### ISSUE THREAD

**Issue by kate502042** [billgreenwald/pgltools#8]
Hello,

I'm a new user of pgltools. Thanks for developing this tool.

I tried 'pgltools formatbedpe myfile.bedpe > myfile.pgl, but I got the following error message

Traceback (most recent call last):
  File "/home/kate146/pgltools-master/sh/../Python/column_flip.py", line 93, in <module>
    header,A=_processFile(args['a'],args['stdInA'])
  File "/home/kate146/pgltools-master/sh/../Python/column_flip.py", line 31, in _processFile
    return header[:-1], [[x[0],int(x[1]),int(x[2]),x[3],int(x[4]),int(x[5]), x[6:]] for x in lines]
ValueError: invalid literal for int() with base 10: 'x1'

myfile.bedpe is 
chr10	97990000	97995000	chr10	98160000	98165000
chr10	95360000	95365000	chr10	95495000	95500000
chr10	82275000	82280000	chr10	82325000	82330000
chr10	79285000	79290000	chr10	79335000	79340000
chr10	80460000	80465000	chr10	80505000	80510000
chr10	60245000	60250000	chr10	60285000	60290000

Would you please help me out for this issue? I'd appreciate it very much.

Kate

**Comment by billgreenwald** [comment]
Does your header line start with a #

**Comment by kate502042** [comment]
Thanks for your reply.

Bedpe file was originally from Juicebox hiccups. So, the format was 

chr1	x1	x2	chr2	y1	y2	name	score	strand1	strand2	color	observed	expectedBL	expectedDonut	expectedH	expectedV	fdrBL	fdrDonut	fdrH	fdrV	numCollapsed	centroid1	centroid2	radius
10	97990000	97995000	10	98160000	98165000	.	.	.	.	0,255,255	18.0	4.32716	5.7680717	5.2278495	4.0104756	0.004191384	0.023361297	0.022777954	0.00418444	2	97997500	98160000	5590
10	95360000	95365000	10	95495000	95500000	.	.	.	.	0,255,255	24.0	8.949469	7.73983	8.279259	8.436993	0.019412663	0.0023937481	0.023240084	0.023300959	3	95360833	95489166	11785
10	82275000	82280000	10	82325000	82330000	.	.	.	.	0,255,255	30.0	10.765405	10.323813	11.625475	9.760296	0.005261822	0.0055158692	0.0071301674	3.8611615E-4	2	82270000	82330000	7906

and I removed header from this file, added 'chr' to $1 and $4 and generated the above file (myfile.bedpe).  I'm not sure about the right format as input..

Kate

**Comment by billgreenwald** [comment]
Thanks for the info!  I may not have been clear -- start your header row
with "#" and the error should go away

**Comment by kate502042** [comment]
I put # for my header, but still saw the same issue. So I tried the following.

I found an example from the previous issue (performance for pgltools merge) as below and tried the exactly same thing, and didn't get any error (this file doesn't have a header). 
----
head encoderoadmap_lasso.1.csv 
chrX:100040000-100041800,ENSG00000000003.10$TSPAN6$chrX$99894988$-,0.49
chrX:100046800-100048000,ENSG00000000003.10$TSPAN6$chrX$99894988$-,0.37
chrX:100128800-100130000,ENSG00000000003.10$TSPAN6$chrX$99894988$-,0.39
chrX:99749000-99751000,ENSG00000000003.10$TSPAN6$chrX$99894988$-,0.47
chrX:99851000-99853000,ENSG00000000003.10$TSPAN6$chrX$99894988$-,0.57
chrX:99854000-99856200,ENSG00000000003.10$TSPAN6$chrX$99894988$-,0.68
chrX:99858800-99859600,ENSG00000000003.10$TSPAN6$chrX$99894988$-,0.59
chrX:99863600-99865600,ENSG00000000003.10$TSPAN6$chrX$99894988$-,0.57
chrX:99866800-99867800,ENSG00000000003.10$TSPAN6$chrX$99894988$-,0.55
chrX:99868400-99868600,ENSG00000000003.10$TSPAN6$chrX$99894988$-,0.55

## convert to pgl format, add 2kb flanking for the promoter site

cat   encoderoadmap_lasso.1.csv | tr "$" ":" |  sed -E 's/(chr[0-9XY]+:[0-9]+-[0-9]+),.+(chr[0-9XY]+:[0-9]+):.+/\1,\2/' | tr ":,-" "\t" | awk -v OFS="\t" '{print $1,$2,$3,$4,$5-2000,$5+2000}' | pgltools formatbedpe |  sed 's/[ \t]*$//'> encoderoadmap_lasso1.bedpe
----
The format of this file before going to 'pgltools formatbedpe' (test.txt;  i.e. cat   encoderoadmap_lasso.1.csv | tr "$" ":" |  sed -E 's/(chr[0-9XY]+:[0-9]+-[0-9]+),.+(chr[0-9XY]+:[0-9]+):.+/\1,\2/' | tr ":,-" "\t" | awk -v OFS="\t" '{print $1,$2,$3,$4,$5-2000,$5+2000}' > test.txt) is 

chrX	100040000	100041800	chrX	99892988	99896988
chrX	100046800	100048000	chrX	99892988	99896988
chrX	100128800	100130000	chrX	99892988	99896988
chrX	99749000	99751000	chrX	99892988	99896988
chrX	99851000	99853000	chrX	99892988	99896988
chrX	99854000	99856200	chrX	99892988	99896988
chrX	99858800	99859600	chrX	99892988	99896988
chrX	99863600	99865600	chrX	99892988	99896988
chrX	99866800	99867800	chrX	99892988	99896988
chrX	99868400	99868600	chrX	99892988	99896988

So, I don't know what is difference between test.txt and myfile.bedpe 
myfile.bedpe is again
chr10	97990000	97995000	chr10	98160000	98165000
chr10	95360000	95365000	chr10	95495000	95500000
chr10	82275000	82280000	chr10	82325000	82330000
chr10	79285000	79290000	chr10	79335000	79340000
chr10	80460000	80465000	chr10	80505000	80510000
chr10	60245000	60250000	chr10	60285000	60290000
chr10	127010000	127015000	chr10	127050000	127055000

This myfile.bedpe generated the same error message regardless of header. 

I generated 'myfile.bedpe' by doing 
cat original.bedpe (Juicebox output as shown above) | tail -n +2 | awk '{$1 = "chr"$1; $4= "chr"$4; print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6}' > myfile.bedpe

I think I should use other commands to generate myfile.bedpe, but I have no idea. Would you please help me out? 

Thank you,
Kate

**Comment by kate502042** [comment]
I did grep chr10 only (cat myfile.bedpe | grep chr10) and now it works! Is this normal that the file should include only one chromosome..?  I need the file for all chromosomes and how could I do this? 

Thank you again!
Kate

**Comment by billgreenwald** [comment]
It should work with multiple chromosomes per file.

Can you upload your files that you tried using so I can test them?

**Comment by kate502042** [comment]
Hi, I've figured out the problem. There was a mistake- a header was inserted in the middle of the input file accidentally. Now, everything works well. Thank you for your time!! 

Kate

**Comment by billgreenwald** [comment]
Glad it works!
